language: cpp

os:
  - osx
compiler:
  - clang

script:
  - brew upgrade openssl
  - git clone https://github.com/Dekken/maiken -b master --depth 1 maiken
  - make bsd CXX=clang++ -C maiken
  - mv maiken/mkn .
  - SSL_INC=/usr/local/opt/openssl/include
  - SSL_LIB=/usr/local/opt/openssl/lib
  - export MKN_LIB_LINK_LIB=1
  - ./mkn build -dtKa "-O2 -std=c++14" -l "-pthread -ldl" -p test run
